### ISSUE TITLE
scrollbar picks up previous input after switching state from off to on.

### ISSUE THREAD

**Issue by tcanbolat** [gilbarbara/disable-scroll#25]
When you try to scroll when the scrollbar state is locked everything works fine, the scrollbar remains stuck in place. however after changing the state to scrollbar on. the scrollbar moves on its own in the direction that the user tried scrolling when it was locked. When the scrollbar is locked it seems to save the state that it was trying to scroll and applies it to the scrollbar after turning it back on. You can replicate this glitch in the code-sandbox demo that is provided in this repo. Just click the button to turn off scrollbar and try scrolling down a couple times, then click the button to turn on scrolling and you will notice the scrollbar move down on its own.  * Edit - this seems to happen only with the touchpad for laptops, key-strokes and mouse-wheel work great!

**Comment by gilbarbara** [comment]
hey @tcanbolat 

I couldn't replicate this behavior in the demo. All the scroll actions performed while it was active didn't trigger scrolling after I deactivate it.
I tested with a trackpad in a MacBook and a mouse with an iMac. Maybe it is a configuration with your own computer?

**Comment by tcanbolat** [comment]
It happens if you switch it off fairly quick, Within a second or so of swiping.
I'm using a Windows 10 laptop and to scroll up or down on the touchpad I am using 2 fingers.
I will also try and see if other laptops are doing this as well.
here is an example video of what's going on.

https://user-images.githubusercontent.com/55068433/103975852-0c31d200-512a-11eb-8ef0-6414995ab83f.mp4

**Comment by gilbarbara** [comment]
This is a super simple package that adds a listener to scroll in order to prevent the default behavior when it's on and remove it when it's off...

If the scroll continues after you lift your fingers and you disable the lock, it's actually doing what it is supposed to do.

Can you check this [post](https://www.dell.com/community/Laptops-General-Read-Only/Trackpad-scroll-drag-still-active-after-I-let-up/td-p/3852604) about the configuration on Windows?

**Comment by tcanbolat** [comment]
That makes sense. thanks for clarifying for me.
